spring.application.name=Spring-Boot-JPA-Practice
# --- MySQL connection ---
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=javauser
spring.datasource.password=java123

# --- JPA / Hibernate settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true